### ISSUE TITLE
Height slider

### ISSUE THREAD

**Issue by LucaHaverty** [finnmprice/newtab#2]
Typing a number on the height slider does not update the slider position

![image](https://github.com/user-attachments/assets/a0cd0834-b214-46c0-bea7-f7285f78d695)
![image](https://github.com/user-attachments/assets/e287880b-511e-485a-80c7-f374c61522b5)
![image](https://github.com/user-attachments/assets/be5b85d4-41c6-478b-8353-17cfa6f80b5b)

> [!CAUTION]
> This gives the product an extreme safety risk because someone might not know what the height is set to and be unable to find the search bar. Fix immediately.

**Comment by finnmprice** [comment]
This was critical. Thank you for bringing this to my attention.
